theme: jekyll-theme-minimal
title: Persona 5 Negotiation Guide
description: Persona 5 & Royal Negotiation Guide. List of questions, answers, and results from shadows.
baseurl: /persona5-negotiation

plugins:
  - jekyll-seo-tag
